---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-sent-news
images:
  - name: stock-sent-news
    newName: stock-sent-news
    newTag: latest
